### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct_perl_runtime#2]
Could you please add license to Perl runtime project?

We use MIT for the majority of runtimes (so they can be included in both GPLv2, GPLv3, BSD-like and commerical projects alike) - see https://github.com/kaitai-io/kaitai_struct_ruby_runtime#licensing. Could you add such clause to your README?

**Comment by ghost** [comment]
OK, I'm here.

**Comment by GreyCat** [comment]
Thanks!
